namespace BinIT2WinIT.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class first1 : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.BinAlerts", "BinId", "dbo.SmartBins");
            DropForeignKey("dbo.RecyclingSubmissions", "VerifiedBy", "dbo.CollectionOfficers");
            DropForeignKey("dbo.CollectionEvents", "DropOffPointId", "dbo.DropOffPoints");
            DropForeignKey("dbo.CollectionOfficers", "DropOffPointId", "dbo.DropOffPoints");
            DropForeignKey("dbo.RecyclingSubmissions", "DropOffPointId", "dbo.DropOffPoints");
            DropForeignKey("dbo.RecyclingSubmissions", "MaterialTypeId", "dbo.MaterialTypes");
            DropForeignKey("dbo.RecyclingSubmissions", "ResidentId", "dbo.Residents");
            DropForeignKey("dbo.CO2Factor", "MaterialTypeId", "dbo.MaterialTypes");
            DropForeignKey("dbo.PointsRates", "MaterialTypeId", "dbo.MaterialTypes");
            DropForeignKey("dbo.PointsTransactions", "ResidentId", "dbo.Residents");
            DropForeignKey("dbo.CommunityStatus", "DropOffPointId", "dbo.DropOffPoints");
            DropForeignKey("dbo.Notifications", "UserId", "dbo.AspNetUsers");
            DropForeignKey("dbo.RedemptionRequests", "OptionId", "dbo.RedemptionOptions");
            DropForeignKey("dbo.RedemptionRequests", "ResidentId", "dbo.Residents");
            DropIndex("dbo.RecyclingSubmissions", new[] { "DropOffPointId" });
            DropIndex("dbo.RecyclingSubmissions", new[] { "VerifiedBy" });
            AddColumn("dbo.CollectionOfficers", "DropOffPoint_DropOffPointId", c => c.Int());
            AddColumn("dbo.CollectionEvents", "DropOffPoint_DropOffPointId", c => c.Int());
            AddColumn("dbo.RecyclingSubmissions", "MaterialType_MaterialTypeId", c => c.Int());
            AddColumn("dbo.RecyclingSubmissions", "DropOffPoint_DropOffPointId", c => c.Int());
            AddColumn("dbo.RecyclingSubmissions", "CollectionOfficer_OfficerId", c => c.Int());
            AddColumn("dbo.CO2Factor", "MaterialType_MaterialTypeId", c => c.Int());
            AddColumn("dbo.PointsRates", "MaterialType_MaterialTypeId", c => c.Int());
            AlterColumn("dbo.AdminCreationAudits", "NewAdminEmail", c => c.String(nullable: false, maxLength: 256));
            AlterColumn("dbo.AdminCreationAudits", "NewAdminName", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.AdminCreationAudits", "CreatedByName", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.AspNetUsers", "FullName", c => c.String(maxLength: 100));
            AlterColumn("dbo.Administrators", "FullName", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.Administrators", "Email", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.Administrators", "Department", c => c.String(maxLength: 50));
            AlterColumn("dbo.Announcements", "Title", c => c.String(nullable: false, maxLength: 200));
            AlterColumn("dbo.Announcements", "TargetAudience", c => c.String(maxLength: 20));
            AlterColumn("dbo.Announcements", "CreatedBy", c => c.String(maxLength: 100));
            AlterColumn("dbo.BinAlerts", "AlertType", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.CollectionOfficers", "FullName", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.CollectionOfficers", "PhoneNumber", c => c.String(maxLength: 20));
            AlterColumn("dbo.CollectionOfficers", "EmployeeNumber", c => c.String(nullable: false, maxLength: 20));
            AlterColumn("dbo.CollectionOfficers", "Department", c => c.String(maxLength: 50));
            AlterColumn("dbo.DropOffPoints", "Name", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.DropOffPoints", "Address", c => c.String(nullable: false, maxLength: 200));
            AlterColumn("dbo.DropOffPoints", "City", c => c.String(maxLength: 50));
            AlterColumn("dbo.RecyclingSubmissions", "DropOffPointId", c => c.Int());
            AlterColumn("dbo.RecyclingSubmissions", "Status", c => c.String(nullable: false, maxLength: 20));
            AlterColumn("dbo.MaterialTypes", "Name", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.MaterialTypes", "Description", c => c.String(maxLength: 200));
            AlterColumn("dbo.Residents", "FullName", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.Residents", "PhoneNumber", c => c.String(nullable: false, maxLength: 20));
            AlterColumn("dbo.Residents", "Address", c => c.String(maxLength: 200));
            AlterColumn("dbo.Residents", "Suburb", c => c.String(maxLength: 50));
            AlterColumn("dbo.Residents", "City", c => c.String(maxLength: 50));
            AlterColumn("dbo.PointsTransactions", "Description", c => c.String(nullable: false, maxLength: 500));
            AlterColumn("dbo.PointsTransactions", "Type", c => c.String(nullable: false, maxLength: 20));
            AlterColumn("dbo.PointsTransactions", "Reason", c => c.String(maxLength: 200));
            AlterColumn("dbo.SmartBins", "BinName", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.CommunityStatus", "Status", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("dbo.CommunityStatus", "Notes", c => c.String(maxLength: 500));
            AlterColumn("dbo.CommunityStatus", "UpdatedBy", c => c.String(maxLength: 100));
            AlterColumn("dbo.Notifications", "Title", c => c.String(nullable: false, maxLength: 200));
            AlterColumn("dbo.Notifications", "Type", c => c.String(maxLength: 50));
            AlterColumn("dbo.Notifications", "Link", c => c.String(maxLength: 500));
            AlterColumn("dbo.RedemptionOptions", "DiscountAmount", c => c.Decimal(nullable: false, precision: 18, scale: 2));
            AlterColumn("dbo.RedemptionOptions", "Icon", c => c.String(maxLength: 50));
            AlterColumn("dbo.RedemptionRequests", "DiscountAmount", c => c.Decimal(nullable: false, precision: 18, scale: 2));
            AlterColumn("dbo.SystemConfigurations", "ConfigKey", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("dbo.SystemConfigurations", "ConfigValue", c => c.String(nullable: false, maxLength: 500));
            AlterColumn("dbo.SystemConfigurations", "Description", c => c.String(maxLength: 500));
            CreateIndex("dbo.CollectionOfficers", "DropOffPoint_DropOffPointId");
            CreateIndex("dbo.CollectionEvents", "DropOffPoint_DropOffPointId");
            CreateIndex("dbo.RecyclingSubmissions", "DropOffPointId");
            CreateIndex("dbo.RecyclingSubmissions", "MaterialType_MaterialTypeId");
            CreateIndex("dbo.RecyclingSubmissions", "DropOffPoint_DropOffPointId");
            CreateIndex("dbo.RecyclingSubmissions", "CollectionOfficer_OfficerId");
            CreateIndex("dbo.CO2Factor", "MaterialType_MaterialTypeId");
            CreateIndex("dbo.PointsRates", "MaterialType_MaterialTypeId");
            AddForeignKey("dbo.BinAlerts", "BinId", "dbo.SmartBins", "BinId");
            AddForeignKey("dbo.RecyclingSubmissions", "CollectionOfficer_OfficerId", "dbo.CollectionOfficers", "OfficerId");
            AddForeignKey("dbo.CollectionEvents", "DropOffPoint_DropOffPointId", "dbo.DropOffPoints", "DropOffPointId");
            AddForeignKey("dbo.CollectionOfficers", "DropOffPoint_DropOffPointId", "dbo.DropOffPoints", "DropOffPointId");
            AddForeignKey("dbo.RecyclingSubmissions", "DropOffPoint_DropOffPointId", "dbo.DropOffPoints", "DropOffPointId");
            AddForeignKey("dbo.CollectionEvents", "DropOffPointId", "dbo.DropOffPoints", "DropOffPointId");
            AddForeignKey("dbo.RecyclingSubmissions", "DropOffPointId", "dbo.DropOffPoints", "DropOffPointId");
            AddForeignKey("dbo.RecyclingSubmissions", "MaterialTypeId", "dbo.MaterialTypes", "MaterialTypeId");
            AddForeignKey("dbo.RecyclingSubmissions", "ResidentId", "dbo.Residents", "ResidentId");
            AddForeignKey("dbo.CO2Factor", "MaterialType_MaterialTypeId", "dbo.MaterialTypes", "MaterialTypeId");
            AddForeignKey("dbo.PointsRates", "MaterialType_MaterialTypeId", "dbo.MaterialTypes", "MaterialTypeId");
            AddForeignKey("dbo.RecyclingSubmissions", "MaterialType_MaterialTypeId", "dbo.MaterialTypes", "MaterialTypeId");
            AddForeignKey("dbo.CO2Factor", "MaterialTypeId", "dbo.MaterialTypes", "MaterialTypeId");
            AddForeignKey("dbo.PointsRates", "MaterialTypeId", "dbo.MaterialTypes", "MaterialTypeId");
            AddForeignKey("dbo.PointsTransactions", "ResidentId", "dbo.Residents", "ResidentId");
            AddForeignKey("dbo.CommunityStatus", "DropOffPointId", "dbo.DropOffPoints", "DropOffPointId");
            AddForeignKey("dbo.Notifications", "UserId", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.RedemptionRequests", "OptionId", "dbo.RedemptionOptions", "OptionId");
            AddForeignKey("dbo.RedemptionRequests", "ResidentId", "dbo.Residents", "ResidentId");
            DropColumn("dbo.RecyclingSubmissions", "IsFlagged");
            DropColumn("dbo.RecyclingSubmissions", "FlagReason");
        }
        
        public override void Down()
        {
            AddColumn("dbo.RecyclingSubmissions", "FlagReason", c => c.String());
            AddColumn("dbo.RecyclingSubmissions", "IsFlagged", c => c.Boolean(nullable: false));
            DropForeignKey("dbo.RedemptionRequests", "ResidentId", "dbo.Residents");
            DropForeignKey("dbo.RedemptionRequests", "OptionId", "dbo.RedemptionOptions");
            DropForeignKey("dbo.Notifications", "UserId", "dbo.AspNetUsers");
            DropForeignKey("dbo.CommunityStatus", "DropOffPointId", "dbo.DropOffPoints");
            DropForeignKey("dbo.PointsTransactions", "ResidentId", "dbo.Residents");
            DropForeignKey("dbo.PointsRates", "MaterialTypeId", "dbo.MaterialTypes");
            DropForeignKey("dbo.CO2Factor", "MaterialTypeId", "dbo.MaterialTypes");
            DropForeignKey("dbo.RecyclingSubmissions", "MaterialType_MaterialTypeId", "dbo.MaterialTypes");
            DropForeignKey("dbo.PointsRates", "MaterialType_MaterialTypeId", "dbo.MaterialTypes");
            DropForeignKey("dbo.CO2Factor", "MaterialType_MaterialTypeId", "dbo.MaterialTypes");
            DropForeignKey("dbo.RecyclingSubmissions", "ResidentId", "dbo.Residents");
            DropForeignKey("dbo.RecyclingSubmissions", "MaterialTypeId", "dbo.MaterialTypes");
            DropForeignKey("dbo.RecyclingSubmissions", "DropOffPointId", "dbo.DropOffPoints");
            DropForeignKey("dbo.CollectionEvents", "DropOffPointId", "dbo.DropOffPoints");
            DropForeignKey("dbo.RecyclingSubmissions", "DropOffPoint_DropOffPointId", "dbo.DropOffPoints");
            DropForeignKey("dbo.CollectionOfficers", "DropOffPoint_DropOffPointId", "dbo.DropOffPoints");
            DropForeignKey("dbo.CollectionEvents", "DropOffPoint_DropOffPointId", "dbo.DropOffPoints");
            DropForeignKey("dbo.RecyclingSubmissions", "CollectionOfficer_OfficerId", "dbo.CollectionOfficers");
            DropForeignKey("dbo.BinAlerts", "BinId", "dbo.SmartBins");
            DropIndex("dbo.PointsRates", new[] { "MaterialType_MaterialTypeId" });
            DropIndex("dbo.CO2Factor", new[] { "MaterialType_MaterialTypeId" });
            DropIndex("dbo.RecyclingSubmissions", new[] { "CollectionOfficer_OfficerId" });
            DropIndex("dbo.RecyclingSubmissions", new[] { "DropOffPoint_DropOffPointId" });
            DropIndex("dbo.RecyclingSubmissions", new[] { "MaterialType_MaterialTypeId" });
            DropIndex("dbo.RecyclingSubmissions", new[] { "DropOffPointId" });
            DropIndex("dbo.CollectionEvents", new[] { "DropOffPoint_DropOffPointId" });
            DropIndex("dbo.CollectionOfficers", new[] { "DropOffPoint_DropOffPointId" });
            AlterColumn("dbo.SystemConfigurations", "Description", c => c.String());
            AlterColumn("dbo.SystemConfigurations", "ConfigValue", c => c.String(nullable: false));
            AlterColumn("dbo.SystemConfigurations", "ConfigKey", c => c.String(nullable: false));
            AlterColumn("dbo.RedemptionRequests", "DiscountAmount", c => c.Decimal(nullable: false, precision: 10, scale: 2));
            AlterColumn("dbo.RedemptionOptions", "Icon", c => c.String());
            AlterColumn("dbo.RedemptionOptions", "DiscountAmount", c => c.Decimal(nullable: false, precision: 10, scale: 2));
            AlterColumn("dbo.Notifications", "Link", c => c.String());
            AlterColumn("dbo.Notifications", "Type", c => c.String());
            AlterColumn("dbo.Notifications", "Title", c => c.String(nullable: false));
            AlterColumn("dbo.CommunityStatus", "UpdatedBy", c => c.String());
            AlterColumn("dbo.CommunityStatus", "Notes", c => c.String());
            AlterColumn("dbo.CommunityStatus", "Status", c => c.String(nullable: false));
            AlterColumn("dbo.SmartBins", "BinName", c => c.String(nullable: false));
            AlterColumn("dbo.PointsTransactions", "Reason", c => c.String());
            AlterColumn("dbo.PointsTransactions", "Type", c => c.String(nullable: false));
            AlterColumn("dbo.PointsTransactions", "Description", c => c.String(nullable: false));
            AlterColumn("dbo.Residents", "City", c => c.String());
            AlterColumn("dbo.Residents", "Suburb", c => c.String());
            AlterColumn("dbo.Residents", "Address", c => c.String());
            AlterColumn("dbo.Residents", "PhoneNumber", c => c.String(nullable: false));
            AlterColumn("dbo.Residents", "FullName", c => c.String(nullable: false));
            AlterColumn("dbo.MaterialTypes", "Description", c => c.String());
            AlterColumn("dbo.MaterialTypes", "Name", c => c.String(nullable: false));
            AlterColumn("dbo.RecyclingSubmissions", "Status", c => c.String(nullable: false));
            AlterColumn("dbo.RecyclingSubmissions", "DropOffPointId", c => c.Int(nullable: false));
            AlterColumn("dbo.DropOffPoints", "City", c => c.String());
            AlterColumn("dbo.DropOffPoints", "Address", c => c.String(nullable: false));
            AlterColumn("dbo.DropOffPoints", "Name", c => c.String(nullable: false));
            AlterColumn("dbo.CollectionOfficers", "Department", c => c.String());
            AlterColumn("dbo.CollectionOfficers", "EmployeeNumber", c => c.String());
            AlterColumn("dbo.CollectionOfficers", "PhoneNumber", c => c.String());
            AlterColumn("dbo.CollectionOfficers", "FullName", c => c.String(nullable: false));
            AlterColumn("dbo.BinAlerts", "AlertType", c => c.String());
            AlterColumn("dbo.Announcements", "CreatedBy", c => c.String());
            AlterColumn("dbo.Announcements", "TargetAudience", c => c.String());
            AlterColumn("dbo.Announcements", "Title", c => c.String(nullable: false));
            AlterColumn("dbo.Administrators", "Department", c => c.String());
            AlterColumn("dbo.Administrators", "Email", c => c.String(nullable: false));
            AlterColumn("dbo.Administrators", "FullName", c => c.String(nullable: false));
            AlterColumn("dbo.AspNetUsers", "FullName", c => c.String());
            AlterColumn("dbo.AdminCreationAudits", "CreatedByName", c => c.String());
            AlterColumn("dbo.AdminCreationAudits", "NewAdminName", c => c.String());
            AlterColumn("dbo.AdminCreationAudits", "NewAdminEmail", c => c.String());
            DropColumn("dbo.PointsRates", "MaterialType_MaterialTypeId");
            DropColumn("dbo.CO2Factor", "MaterialType_MaterialTypeId");
            DropColumn("dbo.RecyclingSubmissions", "CollectionOfficer_OfficerId");
            DropColumn("dbo.RecyclingSubmissions", "DropOffPoint_DropOffPointId");
            DropColumn("dbo.RecyclingSubmissions", "MaterialType_MaterialTypeId");
            DropColumn("dbo.CollectionEvents", "DropOffPoint_DropOffPointId");
            DropColumn("dbo.CollectionOfficers", "DropOffPoint_DropOffPointId");
            CreateIndex("dbo.RecyclingSubmissions", "VerifiedBy");
            CreateIndex("dbo.RecyclingSubmissions", "DropOffPointId");
            AddForeignKey("dbo.RedemptionRequests", "ResidentId", "dbo.Residents", "ResidentId", cascadeDelete: true);
            AddForeignKey("dbo.RedemptionRequests", "OptionId", "dbo.RedemptionOptions", "OptionId", cascadeDelete: true);
            AddForeignKey("dbo.Notifications", "UserId", "dbo.AspNetUsers", "Id", cascadeDelete: true);
            AddForeignKey("dbo.CommunityStatus", "DropOffPointId", "dbo.DropOffPoints", "DropOffPointId", cascadeDelete: true);
            AddForeignKey("dbo.PointsTransactions", "ResidentId", "dbo.Residents", "ResidentId", cascadeDelete: true);
            AddForeignKey("dbo.PointsRates", "MaterialTypeId", "dbo.MaterialTypes", "MaterialTypeId", cascadeDelete: true);
            AddForeignKey("dbo.CO2Factor", "MaterialTypeId", "dbo.MaterialTypes", "MaterialTypeId", cascadeDelete: true);
            AddForeignKey("dbo.RecyclingSubmissions", "ResidentId", "dbo.Residents", "ResidentId", cascadeDelete: true);
            AddForeignKey("dbo.RecyclingSubmissions", "MaterialTypeId", "dbo.MaterialTypes", "MaterialTypeId", cascadeDelete: true);
            AddForeignKey("dbo.RecyclingSubmissions", "DropOffPointId", "dbo.DropOffPoints", "DropOffPointId", cascadeDelete: true);
            AddForeignKey("dbo.CollectionOfficers", "DropOffPointId", "dbo.DropOffPoints", "DropOffPointId");
            AddForeignKey("dbo.CollectionEvents", "DropOffPointId", "dbo.DropOffPoints", "DropOffPointId", cascadeDelete: true);
            AddForeignKey("dbo.RecyclingSubmissions", "VerifiedBy", "dbo.CollectionOfficers", "OfficerId");
            AddForeignKey("dbo.BinAlerts", "BinId", "dbo.SmartBins", "BinId", cascadeDelete: true);
        }
    }
}
